CC = gcc
CFLAGS = -I./include -g -Wall
LDFLAGS = -lreadline
SRCDIR = src
BINDIR = bin
SOURCES = $(SRCDIR)/main.c $(SRCDIR)/shell.c $(SRCDIR)/execute.c $(SRCDIR)/parser.c
OBJECTS = $(SOURCES:.c=.o)
TARGET = $(BINDIR)/myshell

$(TARGET): $(OBJECTS)
	@mkdir -p $(BINDIR)
	$(CC) -o $@ $(OBJECTS) $(LDFLAGS)

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJECTS) $(TARGET)

.PHONY: clean
